# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/main";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd:3" "noatime" "discard=async"];
  };

  boot.initrd.luks.devices."main".device = "/dev/disk/by-uuid/0b9958b7-8bd9-4d33-b22d-a2bfa127b679";

  fileSystems."/home" = {
    device = "/dev/mapper/main";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd:3" "noatime" "discard=async"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/main";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd:3" "noatime" "discard=async"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2FE1-B66F";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
